name = "piecebypiece"
compatibility_date = "2025-07-24"
account_id="4dd8241a9a48040d95ab8579c0d0336a"
workers_dev = true

[site]
bucket = "./Piecebypiecerepo"  # The folder where your built static files live

# Optional for environment variables or other settings
# [env.production]
# route = "https://example.com/*"
# zone_id = "your-zone-id"
